name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.04103dd7-8a27-430b-b984-3b6933f127bf}}
          heroku_app_name: "waifu2" #Must be unique in Heroku
          heroku_email: "uzumakigeto21@gmail.com"
